CREATE TABLE public."TEMPLATE" (
	"TEMPLATEID" varchar(255) NOT NULL,
	"TEMPLATENAME" varchar(255) NOT NULL,
	"SUBJECT" varchar(512) NULL,
	"CONTENT" text NOT NULL,
	"ISACTIVE" boolean NOT NULL DEFAULT true,
	"VERSION" integer NOT NULL DEFAULT 1,
	"CREATEDBY" varchar(255) NOT NULL,
	"CREATEDTIME" timestamp NOT NULL,
	"UPDATEDTIME" timestamp NULL,
	"UPDATEDBY" varchar(255) NULL,
	CONSTRAINT "TEMPLATE_PK" PRIMARY KEY ("TEMPLATEID"),
	CONSTRAINT template_un UNIQUE ("TEMPLATENAME")
);