apiVersion: v1
kind: Service
metadata:
  name: notify-svc
  namespace: desire3d
  labels:
    name: notifysvc
spec:
  type: NodePort
  selector:
        name: notify
        version: "1.0.0"
        release: stable
        tier: fe
        zone: prod
        managed-by: m2
  ports:
  - port: 80
    targetPort: 9999
    protocol: TCP
    name: http